#    -*- mode: org -*-
#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:t reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+OPTIONS: toc:1
#+REVEAL_MARGIN: 0.2
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: none
#+REVEAL_THEME: night
#+REVEAL_EXTRA_CSS: ./presentation.css

#+TITLE: Classical Scale Work and Improvisation
#+AUTHOR: Tom Ed White
#+EMAIL: wtomed@gmail.com

* Introduction

  Play anything that pops into your head.

#+ATTR_REVEAL: :frag t
  Play anything you hear.

#+ATTR_REVEAL: :frag t
  Without thinking, the same way that you talk.

** Me

   I am an amateur musician who performs a lot in the community where I live, in multiple genres.

#+ATTR_REVEAL: :frag t
   Mostly on viola, but I also play the violin, tenor banjo, and I sing a lot.

* Common questions?

* Can I do this?

#+ATTR_REVEAL: :frag t
  Yes we can.
 #+BEGIN_NOTES
 Universal ability, but skill development required.
 
 Estimated time frame: 2nd language.
 #+END_NOTES 
#+ATTR_REVEAL: :frag t
  Should I do this?
#+BEGIN_NOTES
The power to play in multiple genres

Self reliance
#+END_NOTES
* A paradox  
#+ATTR_REVEAL: :frag t
   It comes naturally to everyone.

#+ATTR_REVEAL: :frag t
   But it takes time.
* You have to immerse yourself in a musical community
  There is no substitute for making friends.
  
* You can do a lot on your own
  It's like practicing with Rosetta Stone.

  This type of practicing evolved as an important part of jazz training.

  Jazz people have developed a lot of effective pedagogy, which can be used for any genre.

  This type of practicing and traditional classical scale work overlap somewhat.

  I will show you some of the overlap, and give you a taste of this type of training.

* [[./Images/hrm.pdf][Let's play some scales from Hřímalý]]
 #+BEGIN_NOTES
 Click on the title to open Hřímalý printout.

 Play the first scale through to get everyone comfortable. Skip the middle
 triplets. Play all scales in sequence.

 Encourage violists and cellists to think in terms of one octave scales,
 ignoring the notation in treble clef.

 Close the pdf page. Play D and G patterns from memory. Play A scale, and
 encourage violists and cellists to chose whichever octave they like.

 Repeat with C scale, with the violinists chosing whichever octave they prefer.
 #+END_NOTES 


* [[./Images/hrmc.pdf][Hřímalý without the notes]]

#+BEGIN_NOTES
Play original finger pattern, then different pattern starting on another finger.
#+END_NOTES


* [[./Images/stv.pdf][Ševčík patterns]]

* [[./Images/Phrase-Codex.pdf][Miguel Atwood-Ferguson]]


#+BEGIN_NOTES
Memorize pattern with participants. Pull up circle of fifths and play pattern through D and G major only.

Play the pattern slowly in F. Suggest either playing in 2nd position with the same finger pattern, or playing in 1st position with a different pattern.

Repeat in Bb. 

Discuss playing patterns through the entire circle, shifting or changing finger patterns as needed.
#+END_NOTES

* Make up a pattern

#+BEGIN_NOTES
Invite a volunteer to come forward.

Make up a simple phrase that fits into 4/4 time signature.

Have everyone play together.
#+END_NOTES

* Conclusion

You can memorize the circle of fifths, and become completely comfortable with jumping around the circle.

Get comfortable with playing through the circle with various scale and phrase patterns, without thinking about key sigs.

Make things up; fool around; have fun.

#+ATTR_REVEAL: :frag t
It's a natural but long process, like learning a foreign language. 

#+ATTR_REVEAL: :frag t
Total fluency is a lifelong goal.

#+ATTR_REVEAL: :frag t
If you are participating in a musical community, your rate of progress will skyrocket.

* Next steps
** Song forms  
   Navigate a song without measure numbers or sections designated by letters.
   Learn songs efficiently, using standard forms as a departure point.
** Basic modality and chord symbols
   Get fluency in the five additional diatonic modes, in addition to major and minor.
   
** Chord shapes and forms on violin, viola, and cello
   Put a mando chord chart on this one.
   80% of playing is supporting other players, 20% is soloing. Make this sentence a link.
** Find your voice.
* Resources

This presentation:

https://wtomed.github.io/scale-improv

Please feel free to use it as you see fit, and send me suggestions.

** Miguel Atwood-Ferguson Phrase Codex Site

   [[https://www.dropbox.com/sh/cti43ph1n7mpxc1/AAAv_bbnQMdiSIblPU0tesb8a?dl=0&fbclid=IwAR1j4EJcBzRxL05sQMF2OF7quEyuw6jecJH_DotTA3ONpdbPThhQX-zUwjs]]

** Summer workshops

[[https://christianhowes.com/education/creative-strings-workshop/csw-registration/][Christian Howes]]

[[https://www.markoconnor.com/home][Mark O'Connor]]

[[https://swangathering.com][Swannanoa Summer Gathering]]

