#    -*- mode: org -*-
#+OPTIONS: reveal_center:t reveal_progress:t reveal_history:t reveal_control:t
#+OPTIONS: reveal_mathjax:t reveal_rolling_links:t reveal_keyboard:t reveal_overview:t num:nil
#+OPTIONS: reveal_width:1200 reveal_height:800
#+OPTIONS: toc:1
#+REVEAL_MARGIN: 0.2
#+REVEAL_MIN_SCALE: 0.5
#+REVEAL_MAX_SCALE: 2.5
#+REVEAL_TRANS: none
#+REVEAL_THEME: night
#+REVEAL_EXTRA_CSS: ./presentation.css

#+TITLE: Classical Scale Work and Improvisation
#+AUTHOR: Tom Ed White
#+EMAIL: wtomed@gmail.com

* Introduction

  It is wonderful to play anything that pops into your head.

#+ATTR_REVEAL: :frag t
  It is wonderful to play anything you hear.

#+ATTR_REVEAL: :frag t
  It is wonderful to play the same way that you talk.

** Me

   I am an amateur musician who performs a lot in the community where I live, in multiple genres.

#+ATTR_REVEAL: :frag t
   Mostly on viola, but I also play the violin, tenor banjo, and I sing a lot.
#+BEGIN_NOTES
You don't have to be like me. You don't have to take a fork in the road.
#+END_NOTES
* Common questions?

* Can I do this?

#+ATTR_REVEAL: :frag t
  Yes we can.
 #+BEGIN_NOTES
 Universal ability, but skill development required.
 
 Estimated time frame: 2nd language.
 #+END_NOTES 
#+ATTR_REVEAL: :frag t
  Should I do this?
#+BEGIN_NOTES
The power to play in multiple genres

Self reliance
#+END_NOTES
* A paradox  
#+ATTR_REVEAL: :frag t
   It comes naturally to everyone.

#+ATTR_REVEAL: :frag t
   But it takes time.

* [[./Images/hrm.pdf][Let's play some scales from Hřímalý]]

 #+BEGIN_NOTES
 Click on the title to open Hřímalý printout.

 Play the first scale through to get everyone comfortable. Skip the middle
 triplets. Play all scales in sequence.

 Encourage violists and cellists to think in terms of one octave scales,
 ignoring the notation in treble clef.

 Close the pdf page. Play D and G patterns from memory. Play A scale, and
 encourage violists and cellists to chose whichever octave they like.

 Repeat with C scale, with the violinists chosing whichever octave they prefer.
 #+END_NOTES 

* [[./Images/hrmc.pdf][Hřímalý without the notes]]

#+BEGIN_NOTES
Play original finger pattern, then different pattern starting on another finger.
#+END_NOTES

* [[./Images/stv.pdf][Ševčík patterns]]

#+BEGIN_NOTES
Memorize pattern with participants. Pull up circle of fifths and play pattern through D and G major only.

Play the pattern slowly in F. Suggest either playing in 2nd position with the same finger pattern, or playing in 1st position with a different pattern.

Repeat in Bb. 

Discuss playing patterns through the entire circle, shifting or changing finger patterns as needed.
#+END_NOTES

